USE DATABASE MODECRAFT_ECOMMERCE;
USE SCHEMA PUBLIC;

SELECT * 
FROM modecraft_blob_data
WHERE table_name = 'MODECRAFT_BLOB_DATA'
ORDER BY last_load_time DESC;


/**********************************/
/***** Top products by revenue *****/
/**********************************/

CREATE OR REPLACE TABLE EDA_TOP_PRODUCTS_REVENUE (
    DESCRIPTION STRING,
    REVENUE FLOAT
);

INSERT INTO EDA_TOP_PRODUCTS_REVENUE
SELECT
    DESCRIPTION,
    SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM MODECRAFT_BLOB_DATA
GROUP BY DESCRIPTION
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT * FROM EDA_TOP_PRODUCTS_REVENUE;


/**********************************/
/***** Top products by volume *****/
/**********************************/

CREATE OR REPLACE TABLE EDA_TOP_PRODUCTS_VOLUME (
    DESCRIPTION STRING,
    QUANTITY FLOAT
);

INSERT INTO EDA_TOP_PRODUCTS_VOLUME
SELECT
    DESCRIPTION,
    SUM(QUANTITY) AS TOTAL_VOLUME
FROM MODECRAFT_BLOB_DATA
GROUP BY DESCRIPTION
ORDER BY TOTAL_VOLUME DESC
LIMIT 10;

SELECT * FROM EDA_TOP_PRODUCTS_VOLUME;


/**********************************/
/********* MONTHLY REVENUE ********/
/**********************************/

CREATE OR REPLACE TABLE EDA_MONTHLY_REVENUE (
    MONTH_START DATE,
    TOTAL_REVENUE FLOAT
);

INSERT INTO EDA_MONTHLY_REVENUE
WITH cleaned_data AS (
    SELECT 
        TO_TIMESTAMP_NTZ(INVOICEDATE, 'MM/DD/YY HH24:MI') AS CLEANED_DATE,
        QUANTITY,
        UNITPRICE
    FROM MODECRAFT_BLOB_DATA
)
SELECT
    DATE_TRUNC('MONTH', CLEANED_DATE) AS MONTH_START,
    SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM cleaned_data
GROUP BY MONTH_START
ORDER BY MONTH_START;

SELECT * FROM EDA_MONTHLY_REVENUE;


/**********************************/
/**** WEEKEND VS WEEKDAY ORDERS ***/
/**********************************/

CREATE OR REPLACE TABLE EDA_WEEKEND_WEEKDAY (
    DAY_TYPE STRING,
    TOTAL_ORDERS NUMBER
);

INSERT INTO EDA_WEEKEND_WEEKDAY
SELECT 
    CASE 
        WHEN EXTRACT(DAYOFWEEK, TO_TIMESTAMP_NTZ(INVOICEDATE, 'MM/DD/YY HH24:MI')) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS DAY_TYPE,
    COUNT(*) AS TOTAL_ORDERS
FROM MODECRAFT_BLOB_DATA
GROUP BY DAY_TYPE
ORDER BY TOTAL_ORDERS DESC;

SELECT * FROM EDA_WEEKEND_WEEKDAY;


/**********************************/
/******* COUNTRY TOP REVENUE ******/
/**********************************/

CREATE OR REPLACE TABLE EDA_COUNTRY_REVENUE (
    COUNTRY STRING,
    TOTAL_REVENUE FLOAT
);

INSERT INTO EDA_COUNTRY_REVENUE
SELECT 
    COUNTRY,
    SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM MODECRAFT_BLOB_DATA
GROUP BY COUNTRY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT * FROM EDA_COUNTRY_REVENUE;